d = input('Digite algo:')
print('O tipo primitivo do que foi digitado é:', type(d))
print('O valor digitado é letra?', d.isalpha())
print('O valor digitado é numérico?', d.isnumeric())
print('O valor digitado está em minúsculo?', d.islower())
print('O valor digitado está em maiúsculo?', d.isupper())
print('O valor digitado está tem apenas espaços?', d.isspace())
print('O valor digitdo é alfa-numérico?', d.isalnum())
print('O valor digitado está capitalizaso?', d.istitle())
